server:
  host: localhost
  port: 8080
  mode: debug

datasource:
  mysql:
    host: 47.110.74.7
    port: 3306
    user: root
    password: 123
    db-name: mini-blog

logs:
  path: logs/


jwt:
  secret: github.com/nanfeng.dev/tentcoo/2025.12.28
  iss: github.com/nanfeng.dev
  exp: 3600
  